services:
  - type: web
    name: speen-server
    env: node
    rootDir: speen/server
    buildCommand: npm install
    startCommand: node src/index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: SQLITE_PATH
        value: /var/data/data.sqlite
    disk:
      name: sqlite
      mountPath: /var/data
      sizeGB: 1
